language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'

script:
    - ./gradlew clean build test jacocoTestReport check

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - .utility/initiate-publish.sh

cache:
  directories:
    - $HOME/.gradle

env:
  global:
  - secure: sm5DlYyXxHE5Ak4zlXu1xG+QcJ5HQHw16I3e73F9YaZgdPKrV/9G+vxjgrYeurxzlf8Z9qoW9nncQfufutv/7WAhwQybAEyJx9CEKO4zgFjWfUKKQAwY/tf9AyKibfrb+XEAnm29ab8Anhb8Yoz0ShJENzY9XV8hwU++kGVFCQmrdi5Dro+dlwQONjkaUHuVS3hJWAOqP3uO+204kT0ZfU+gcWJxDs9EYgot74fqp5ly6MkaYzs4nUZh5UhnFhGu7Z8U70eyNiAuJVKDLToQZuR1DVYpfU5OX5w5XlpK/w/1l5CBeptPu50jAI2kB7+YG78KoIbWW6QW6lxi+icpP1rDPvyWeOLrCefe/tNszDZwnkz9QghnQ4l73sG8oZ2c2IIyWxh3ZQrDpk13+lS0w80ibHq8I4IJv3KYhy/Wt+6Wx8KTip0fhWBEpdCPbYPB/S24iQb5z7yDpeD9rX4qiiEwvrwdvnW3LsjHoOddF8ETQuJF4+yaYNoiCt9qmFefI3FwBixJmxIgYdinpVZxMbLNUSMD4XSXRIOs3uMdhZlpQcWzWyPBI6WvZKJXdIHXuTNIPZ1T78Ro8RNmI/EGE0DAYI8G6n5QAm4ilTzn8zyF20xV4iI0rgxAgyBkmUYcTWRm/BYceCkltE0RbgLWbLXk0InSpMP3g8eyu1xNIgI=
  - secure: dIWiyUfprIqYaPPpmnawWxdlcbDKWwGhLM+k76mB0aiz1vuds+vnIjy7HKFpA0UcShLAK1RZZ2jxJiczNFX2DpDIpnQ6+nS2QNeeJPqfog77Dff2U5os05xm0u5cZYMB/E0gWMCR0gvTWRTApLcIfitXsKD16IV60xkaF5m0Gr1DE5u/1454iIVdepExUvb00EMGflJmUL94Ab3GoEhZF5/IArCiRdt56bkiiJedeSI+SDmrpViS4cU9c6Yz4+LjSsSp1e0x7ZGlb0SiCpwACjpEq2k3zJKZIONfsS/b2sQYIoVlzrbFtRcHOZhCH+6JUNndC9mQUUjIHeopTBaq5tYzZPj/GAzZ+NRy2A2hj3JsMbYXASyQDREkp3GaNoRrgDethlKA3bbGXt6Arf/6lKVxKXDHX7AQ/P8jE1G0EQJK40ECb13PEVW4//rnh16srDDT879QcMjDRKoUayz9qddxWV40KfhU88bgSK7XZfsyEgjhMStvVdhsjY53xTooTJn9vNis4UXet2s9Pq6MIApM4P/2hngSniVGHPgETPCHzJVwoSxNpv4ND760NqtQTYzBkC/52zVZLUp7gbxNsZFQNmVeM/ayUKtSN9U/v8cfkiK7QxFOYOb/vrE9YBeaZeuYMzxaCFCN4MlOjW9742hQBVSJPJO2rsNl9Tx+m+o=